# ---- Base Node ----
FROM node:14-alpine AS base
WORKDIR /app
COPY package*.json ./
RUN npm set progress=false && npm config set depth 0 && npm cache clean --force
RUN npm install --only=production && cp -R node_modules production_node_modules
RUN npm install

# ---- Dependencies and Build ----
FROM base AS build
WORKDIR /app
COPY . .
RUN npm run build

# ---- Release ----
FROM nginx:stable-alpine AS release
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build /app/build .
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
