name: Docker Image CI

on:
  push:
    branch: main

jobs:

  Docker:

    runs-on: ubuntu-latest
    

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - uses: docker/setup-qemu-action@v1
      
      - uses: docker/setup-buildx-action@v1
      
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-asnil
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            asnil/subweb-tsutsu:latest
            asnil/subweb-tsutsu:${{ steps.date.outputs.today }}         
